# Generated by Django 3.1.1 on 2020-09-24 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=8)),
                ('dv', models.CharField(default='0', max_length=1)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=255)),
                ('reserva', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ENTREGADA', 'ENTREGADA'), ('LISTA', 'LISTA'), ('PREPARACION', 'PREPARACION')], default='PREPARACION', max_length=11)),
                ('hora_ini', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_ter', models.DateField(blank=True, null=True)),
                ('detalle', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
                ('mesa', models.IntegerField()),
            ],
        ),
    ]
