# Generated by Django 3.1.1 on 2020-10-18 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ATENDIDA', 'ATENDIDA'), ('SIN_ATENCION', 'SIN_ATENCION')], default='SIN_ATENCION', max_length=14)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mesa')),
            ],
        ),
    ]
