# Generated by Django 3.1.1 on 2020-10-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orden_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='grupo',
            field=models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('PLATO_FONDO', 'PLATO_FONDO'), ('APERITIVO', 'APERITIVO'), ('AGREGADO', 'AGREGADO'), ('BEBESTIBLE', 'BEBESTIBLE'), ('POSTRE', 'POSTRE')], default='ENTRADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='receta',
            name='sub_grupo',
            field=models.CharField(choices=[('SOPAS', 'SOPAS'), ('CREMAS', 'CREMAS'), ('CARNES_ROJAS', 'CARNES_ROJAS'), ('CARNES_BLANCAS', 'CARNES_BLANCAS'), ('PESCADOS', 'PESCADOS'), ('MARISCOS', 'MARISCOS'), ('CALDOS', 'CALDOS'), ('LEGUMBRES', 'LEGUMBRES'), ('PASTELES', 'PASTELES'), ('EMBUTIDOS', 'EMBUTIDOS'), ('EMPANADAS', 'EMPANADAS'), ('VINOS', 'VINOS'), ('BEBIDAS', 'BEBIDAS'), ('JUGOS', 'JUGOS'), ('BAJATIVO', 'BAJATIVO'), ('HELADOS', 'HELADOS'), ('TORTAS', 'TORTAS'), ('KUCHENS', 'KUCHENS')], max_length=20),
        ),
    ]
