# Generated by Django 3.1.1 on 2020-09-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200923_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='minutos',
            field=models.IntegerField(default=5),
        ),
    ]
