# Generated by Django 3.1.1 on 2020-09-26 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orden_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='detalle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orden',
            name='hora_ini',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orden',
            name='mesa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='minutos',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
