# Generated by Django 3.1.1 on 2020-10-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201008_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='sub_grupo',
            field=models.CharField(choices=[('SOPAS', 'SOPAS'), ('CREMAS', 'CREMAS'), ('CARNES_ROJAS', 'CARNES_ROJAS'), ('CARNES_BLANCAS', 'CARNES_BLANCAS'), ('PESCADOS', 'PESCADOS'), ('MARISCOS', 'MARISCOS'), ('CALDOS', 'CALDOS'), ('LEGUMBRES', 'LEGUMBRES'), ('PASTELES', 'PASTELES'), ('EMBUTIDOS', 'EMBUTIDOS'), ('EMPANADAS', 'EMPANADAS'), ('VINOS', 'VINOS'), ('BEBIDAS', 'BEBIDAS'), ('JUGOS', 'JUGOS'), ('BAJATIVO', 'BAJATIVO'), ('HELADOS', 'HELADOS'), ('TORTAS', 'TORTAS'), ('KUCHENS', 'KUCHENS'), ('OTRO', 'OTRO')], max_length=20),
        ),
    ]
