# Generated by Django 3.1.1 on 2020-09-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200925_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField(blank=True)),
                ('disponibilidad', models.CharField(choices=[('OCUPADA', 'OCUPADA'), ('RESERVADA', 'RESERVADA'), ('DISPONIBLE', 'DISPONIBLE')], default='DISPONIBLE', max_length=11)),
            ],
        ),
    ]
