# Generated by Django 3.1.1 on 2020-10-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('PAGO', 'PAGO'), ('SOLICITUD', 'SOLICITUD')], default='PAGO', max_length=14),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('ATENDIDA', 'ATENDIDA'), ('SIN_ATENCION', 'SIN_ATENCION'), ('APROBADA', 'APROBADA'), ('RECHAZADA', 'RECHAZADA')], default='SIN_ATENCION', max_length=14),
        ),
    ]
