# Generated by Django 3.1.1 on 2020-10-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201008_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('CREDITO/DEBITO', 'CREDITO/DEBITO')], default='EFECTIVO', max_length=14),
        ),
    ]
