# Generated by Django 3.1.1 on 2020-09-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('detalle', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
