# Generated by Django 3.1.1 on 2020-09-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='embalaje',
            field=models.CharField(choices=[('GRANEL', 'GRANEL'), ('ENVAZADO', 'ENVAZADO')], default='GRANEL', max_length=11),
        ),
    ]
