# Generated by Django 3.1.1 on 2020-10-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200929_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ingredientes', models.CharField(max_length=255)),
                ('t_preparacion', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('grupo', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('PLATO_FONDO', 'PLATO_FONDO'), ('APERITIVO', 'APERITIVO'), ('AGREGADO', 'AGREGADO'), ('BEBESTIBLE', 'BEBESTIBLE'), ('BAJATIVO', 'BAJATIVO'), ('POSTRE', 'POSTRE')], default='ENTRADA', max_length=20)),
                ('sub_grupo', models.CharField(choices=[('SOPAS', 'SOPAS'), ('CREMAS', 'CREMAS'), ('CARNES_ROJAS', 'CARNES_ROJAS'), ('CARNES_BLANCAS', 'CARNES_BLANCAS'), ('PESCADOS', 'PESCADOS'), ('MARISCOS', 'MARISCOS'), ('CALDOS', 'CALDOS'), ('LEGUMBRES', 'LEGUMBRES'), ('PASTELES', 'PASTELES'), ('EMBUTIDOS', 'EMBUTIDOS'), ('EMPANADAS', 'EMPANADAS'), ('VINOS', 'VINOS'), ('BEBIDAS', 'BEBIDAS'), ('JUGOS', 'JUGOS'), ('HELADOS', 'HELADOS'), ('TORTAS', 'TORTAS'), ('KUCHENS', 'KUCHENS')], max_length=20)),
            ],
        ),
    ]
