# Generated by Django 3.1.1 on 2020-10-04 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso', models.IntegerField(default=0)),
                ('egreso', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('detalle', models.CharField(max_length=255)),
            ],
        ),
    ]
